modLoader = "javafml"
loaderVersion = "[36,)"
license = "BSD-3-Clause"
[[mods]]
modId = "cc_fp"
version = "1.5.1"
displayName = "Floo Powder"
authors = "CC2001"
description = "Floo Powder - The Easier Way to Teleport\n\nFound more: https://github.com/C20C01/Floo_Powder"